name: {{cookiecutter.package_name}}_dev_env
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8
  - entrypoints
  - flake8
  - ipython
  - jedi
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pep8
  - pip
  - pylint
  - pytest
  - python>=3.7
  - requests
  - rope
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - sphinx
  - sphinxcontrib
  - sympy
  - yapf
  - pip:
    - black
